### ISSUE TITLE
print(f'Downloading {self.name[:-15]}') SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by maferv** [vaibhavk97/GoBooDo#15]
Hi, I'm trying to use this on GNU/Linux and I'm getting this message.

```
python GoBooDo.py --id=IDNpDwAAQBAJ
  File "GoBooDo.py", line 79
    print(f'Downloading {self.name[:-15]}')
                                         ^
SyntaxError: invalid syntax
```

**Comment by vaibhavk97** [comment]
Kindly use python3 for running the program.

**Comment by maferv** [comment]
Hi @vaibhavk97, thanks for the tip!
Now I'm using python3, installed all the required dependencies, pointed the config to the tesseract binary.

The program works! looks and feels amazing! I'll explore it further but I'm very pleased with it. 
I get the feeling that the more popular it becomes, the more they will try to block it. It's very unfair that they can digitize all these books and then hoard them away, specially all the royalty free books.

I was just thinking that the "Copyrighted material" watermark could be blurred with imagemagick. But the size and position of the area to blur will vary according to the resolution.

By the way, what is the highest resolution one can use? Does it depend on the book? I just set "5000" as the resolution, and the images I'm getting are 1875x2500. What's the standard?

Thank you

**Comment by vaibhavk97** [comment]
Hi @maferv thanks for your valuable comments, glad that GoBoodo was of use to you. Indeed, with the popularity of this program, Google might change its blocking criteria but no protection is good enough :). 

Yes, that's a good suggestion, blurring the "copyrighted image" watermark can also be done. Instead of simply blurring a particular area of the book, a computer vision-based method can be devised which actively blurs the selected part of the text. Will consider it in the future releases of the tool.

Yes, the final resolution is limited to what you are getting, that's the upper limit which google provides.
