### ISSUE TITLE
Trouble with getting code to work

### ISSUE THREAD

**Issue by danlib123** [vaibhavk97/GoBooDo#35]
I have installed Python 3.6 (64 bit), its requirements and made it work on Windows CMD. When I enter the code, python GoBooDo.py --id=XUwOtdcIWdkC within the directory it is stored in in Windows CMD nothing happens. 

What could be the reason behind this?

**Comment by sfolje0** [comment]
> 
> 
> I have installed Python 3.6 (64 bit), its requirements and made it work on Windows CMD. When I enter the code, python GoBooDo.py --id=XUwOtdcIWdkC within the directory it is stored in in Windows CMD nothing happens.
> 
> What could be the reason behind this?

Hi @danlib123,
could you be more specific and tell us more about the situation? 

Because I cannot quite figure out the problem from the description that you wrote.
What do you mean by "nothing happens" (no output is written in cmd console, no output files are created, ... etc. )? What do you mean by "made it work" (Does the basic command `python` work on cmd? Which version of python is shown, when you type `python` in cmd?, etc.)?
