### ISSUE TITLE
Error with tesseract and PDF creation

### ISSUE THREAD

**Issue by riyanimbekar** [vaibhavk97/GoBooDo#53]
After exactly following the instructions you have provided, I am constantly coming across an error (**refer to the screenshot for details**). And being a first time python user, I am unable to identify where am I going wrong, Please assist me in getting rid of this error. Thanks in advance.

![Screenshot (456)](https://user-images.githubusercontent.com/70324158/126873416-d77ec8e7-e370-4df2-b212-cd571d40de79.png)

**Comment by minamotorin** [comment]
# Cause

Are there images on `Images` folder on `[BOOK ID]` folder? The message `C:\program Files\Tesseract-OCR\tesseract.exe is not installed or it's not in your PATH. See README file for more information.` is the answer of what’s wrong. `storeImages.py` failed and no image was saved. So `makePDF.py` failed because there is no image for create PDF.

# Solution

Change `C:\\program Files\\Tesseract-OCR\\tesseract.exe` of `settings.json` to path where `tesseract.exe` is (if you don't have, download [`tesseract.exe`](https://tesseract-ocr.github.io/tessdoc/Downloads)). (Or put `tesseract.exe` on `C:\\program Files\\Tesseract-OCR\\tesseract.exe`.)

Good luck, have fun!

**Comment by minamotorin** [comment]
Same as #32.
