### ISSUE TITLE
What is the current state? Is it still working?

### ISSUE THREAD

**Issue by MateuszPatula** [vaibhavk97/GoBooDo#79]
Has anyone had any luck downloading books recently? I keep receiving the message:

Downloading (a book's title)
Received invalid response.

I've already tried every possible solution mentioned on a support forum :/

**Comment by Historical-17** [comment]
Yes it's still working, for me I first to changed some stuff (install tesseract .exe & replace some code) all what you can be found in the forum (closed issues)

**Comment by MateuszPatula** [comment]
Thanks for letting me know, buddy! I will retry all solutions and their combinations once again. BTW, are you from Europe?

**Comment by Historical-17** [comment]
@MateuszPatula  No sir , I'm Arabian

**Comment by Historical-17** [comment]
also a i downloaded a book today , proxy didn't work (for original proxylist) it showed "Received invalid response" but everything is fine - from fetching links to pdf creation-

**Comment by MateuszPatula** [comment]
Can you somehow send me the edited files which you use? I'm applying the solutions from closed issued, but it doesn't work. Still trying tho...

**Comment by MateuszPatula** [comment]
What I did:
— changed county to my country in the settings.json file (co.in >>> pl)
— this: https://github.com/vaibhavk97/GoBooDo/issues/63#issuecomment-1045965832
— this: https://github.com/vaibhavk97/GoBooDo/issues/60#issuecomment-918563558
Thank you guys!

**Comment by MateuszPatula** [comment]
What I did:
— changed county to my country in the settings.json file (co.in >>> pl)
— this: https://github.com/vaibhavk97/GoBooDo/issues/63#issuecomment-1045965832
— this: https://github.com/vaibhavk97/GoBooDo/issues/60#issuecomment-918563558
Thank you guys!

**Comment by Historical-17** [comment]
so,you are done with it , good luck .
also i want to inform you that i've downloaded 2 books and this tool is useless to me because most pages show (image not available) . i worked all the day for nothing , the problem is one of the books is LOST FROM THE INTERNET and nobody can get it even with money. anyway , what about u ? did u face the same problem with ur book?

**Comment by MateuszPatula** [comment]
Man! It's the worst when your book is nowhere to be found :/ Have you checked libgen.rs or z-library? I can buy my book (it's freaking expensive though), there're some guys on reddit claiming to have .pdf, but I don't want to be scammed LOL So here I am, checking this tool out. And now I see there was some issue, hahhaha, IndexError: list index out of range. But I'm too tired already XDD I will do it tomorrow XD Thx once again, and good luck as well!

**Comment by Historical-17** [comment]
The only place for "SOME" of my books is google books and foreign libraries ( the total number of books i'am looking for right now is about 5 books), just google books ,they aren't elsewhere in the internet , but there still a little hope----------------- one of these books are LOST FOREVER it isn't in google books , amazon neither in manuscript libraries  - not even in that big manuscript library in Paris, nobody ever found it . not me neither anybody else - the only thing we know about it is the title and description which is mentioned in an earlier manuscript. also there are many other lost books i encountered in my research . there is no hope to find them in any place in the world. the problem is almost nobody knows these books - these lost books are one-of a kind .
 you are lucky that u can get ur books from the internet even with money ^_^

**Comment by Historical-17** [comment]
Also if u need any help with goboodo i can help :)

**Comment by Historical-17** [comment]
Oops ,it seems that google books banned my ip or something , it showed like this [image](https://www.lifewire.com/thmb/-ObxKh6nac2-Sy3-htgCksxJmt4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/google-search-error-db3d53300aa64c9d8a5db38351bdc2b3.jpg)

**Comment by MateuszPatula** [comment]
OMG, what kind of books are they? If you don't mind me asking. Are you trying to find out how to make horcruxes? LOL

**Comment by Historical-17** [comment]
They
1- zoology
2-treasure book (seriously)  
3-History
4- mechanics
5- machinery 
Believe me or not there were rockets and Torpedos in 1200s , but according to google the first Torpedo was in 1800s - wrong

**Comment by MateuszPatula** [comment]
I see! Good luck finding them soon! :D
